
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: attested-hello-python
spec:
  selector:
    matchLabels:
      app: attested-hello-python
  replicas: 1
  template:
    metadata:
      labels:
        app: attested-hello-python
    spec:
      containers:
      - name: attested-hello-python
        image: kumarsendhi/hello-python:v6
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: SCONE_CAS_ADDR

          value: 4-2-1.scone-cas.cf

        - name: SCONE_CONFIG_ID

          value: faceapi-25885-27398~hello-k8s-scone/application

        - name: SCONE_LAS_ADDR
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        resources:
          limits:
            sgx.k8s.io/sgx: 1

---
apiVersion: v1
kind: Service
metadata:
  name: attested-hello-python-service
spec:
  selector:
    app: attested-hello-python
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer